spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mss
    username: ${username.local}
    password: ${password.local}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:/db.changelog/changelog-master.xml

jwt:
  secret:
    access: ${jwt.secret.access}
    refresh: ${jwt.secret.refresh}
  expiration:
    access: 10
    refresh: 30
